force-app/main/default/objects/WorkingWatch__c/WorkingWatch__c.object-meta.xml
<CustomObject>
    <description>商談を操作した時間を管理する。</description>
    <label>作業時間</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>作業時間名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkingWatch__c/fields/CalculateTime__c.field-meta.xml
<CustomField>
    <fullName>CalculateTime__c</fullName>
    <description>ストップウォッチの経過時間を保持する。</description>
    <label>計測時間（分）</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StopWatchController.cls
public with sharing class StopWatchController {
    public WorkingWatch__c workingWach {get; set;}	//作業時間オブジェクト
    public String calculateTime {get; set;}			//計測時間（秒）
    public String resultMessage {get; set;}			//登録結果メッセージ
    
    //商談選択リスト
    public List<SelectOption> opportunitySelectOptions{
        get{ 
            List<Opportunity> OpportunityList = [SELECT id, name FROM Opportunity LIMIT 100];
            List<SelectOption> opportunitySelectOptions = new List<SelectOption>();
            for(Opportunity o : OpportunityList){
                opportunitySelectOptions.add(new SelectOption(o.id, o.name));
            }
            return opportunitySelectOptions;
        }
    }
    
    //コンストラクタ
    public StopWatchController(){
        //変数初期化
        this.workingWach = new WorkingWatch__c();
        this.calculateTime = '0';
        this.resultMessage = '';
    }
    
    //登録
    public void register(){
        this.workingWach.CalculateTime__c = this.calculateTime;
        try{
            insert this.workingWach;
            this.resultMessage = '登録しました。';
        }catch(DmlException e){
            for (Integer i = 0; i < e.getNumDml(); i++) {
                this.resultMessage += e.getDmlMessage(i) + '\r\n';
            }
        }
        this.workingWach = new WorkingWatch__c();
    }
}